# Generated by Django 3.2.5 on 2021-07-26 08:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'blank': 'این فیلد اجباریست', 'unique': 'کاربر با این لقب وجود دارد'}, help_text='اجباری. حداکثر تعداد کاراکتر 150 است. فقط میتوانید از اعداد، حروف، @، .، +، -، _ استفاده کنید', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='لقب')),
                ('first_name', models.CharField(error_messages={'blank': 'این فیلد اجباریست'}, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(error_messages={'blank': 'این فیلد اجباریست'}, max_length=150, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(error_messages={'blank': 'این فیلد اجباریست'}, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل')),
                ('is_vip', models.BooleanField(blank=True, default=False, verbose_name='ویژه')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
