# Generated by Django 3.2.5 on 2021-08-01 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'این فیلد اجباریست'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل'),
        ),
    ]
