# Generated by Django 3.2.5 on 2021-08-19 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='عنوان', max_length=100, null=True, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, help_text='عکسی که برای پست نمایش داده میشود', null=True, upload_to='%Y/%M/%D', verbose_name='عکس')),
                ('body', models.TextField(help_text='متن اصلی پست', max_length=500, verbose_name='متن پست')),
                ('like', models.PositiveBigIntegerField(help_text='تعداد افرادی که از این پست خوششان آمده است', verbose_name='پسند')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', related_query_name='User', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-date'],
            },
        ),
    ]
