# Generated by Django 3.2.5 on 2021-08-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.PositiveBigIntegerField(default=0, help_text='تعداد افرادی که از این پست خوششان آمده است', verbose_name='پسند'),
        ),
    ]
