# Generated by Django 3.2.5 on 2021-08-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='عکسی که برای پست نمایش داده میشود', null=True, upload_to='%y/%m/%d', verbose_name='عکس'),
        ),
    ]
