# Generated by Django 3.2.5 on 2021-09-18 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0009_auto_20210918_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(default=None, help_text='تعداد افرادی که این پست را پسندیده اند', related_name='LikeActivity', related_query_name='likeactivity', through='post.LikeActivity', to=settings.AUTH_USER_MODEL, verbose_name='پسند'),
        ),
    ]
